/* eslint-disable no-inline-comments */
module.exports = {
    BOT_USER_ID: '',
    BOT_CHANNEL_ID: '',
    BOT_CATEGORY_ID: '',
    GUILD_ID: '',
    MOD_ROLE_ID: '631566640277880872',
    DEV_ID: '162434234357645312',
    SUGGESTIONS_CHANNEL_ID: '631088127972474880',
    MAP: 'https://i.imgur.com/kDIh5uF.png',
    REINCARNATIONS: 'https://i.imgur.com/npEmtsf.png',
    MINING_NODES: 'https://i.imgur.com/xla6iOC.png',
    INFUSIONS: 'https://i.imgur.com/bbDlfpp.png',
    NEW_MEMBER_DATA: {
        'name': '',
        'warnings': 0,
        'tempBans': 0,
        'cookies': 0,
        'warningreasons': [],
        'mutecount': 0,
        'mutehistory': ['\u200B'],
    },
    HERO_LIST: {
        'npc_dota_hero_kunkka': 'Novice',
        'npc_dota_hero_dragon_knight': 'Warrior',
        'npc_dota_hero_invoker': 'Devout',
        'npc_dota_hero_windrunner': 'Ranger',
        'npc_dota_hero_bounty_hunter': 'Rogue',
        'npc_dota_hero_warlock': 'Mage',
        'npc_dota_hero_axe': 'Brute',
        'npc_dota_hero_juggernaut': 'Samurai',
        'npc_dota_hero_swordsman': 'Swordsman',
        'npc_dota_hero_furion': 'Exile',
        'npc_dota_hero_lina': 'Elementalist',
        'npc_dota_hero_troll_warlord': 'Monk',
        'npc_dota_hero_dazzle': 'Cultist',
        'npc_dota_hero_sniper': 'Hunter',
        'npc_dota_hero_riki': 'Wetboy',
        'npc_dota_hero_crystal_maiden': 'Arcanist',
        'npc_dota_hero_phantom_lancer': 'Lancer',
        'npc_dota_hero_beastmaster': 'Barbarian',
        'npc_dota_hero_brewmaster': 'Exile',
        'npc_dota_hero_drow_ranger': 'Marksman',
        'npc_dota_hero_sven': 'Zerker',
        'npc_dota_hero_silencer': 'Runecaster',
        'npc_dota_hero_arc_warden': 'Technologist',
        'npc_dota_hero_legion_commander': 'Avenger',
        'npc_dota_hero_omniknight': 'Paragon',
        'npc_dota_hero_keeper_of_the_light': 'Bishop',
        'npc_dota_hero_chaos_knight': 'Daeagon',
        'npc_dota_hero_ember_spirit': 'Bladerider',
        'npc_dota_hero_oracle': 'Chronomancer',
        'npc_dota_hero_phantom_assassin': 'Spectre',
        'npc_dota_hero_rubick': 'Wetboy',
        'npc_dota_hero_vengefulspirit': 'Witch',
        'npc_dota_hero_spectre': 'Shadow_Assassin',
        'npc_dota_hero_huskar': 'Beast',
        'npc_dota_hero_chen': 'Bishop',
        'npc_dota_hero_earth_spirit': 'Martial-Artist',
        'npc_dota_hero_antimage': 'Bloodmage',
        'npc_dota_hero_skeleton_king': 'Knight',
        'npc_dota_hero_mirana': 'Priestess',
        'npc_dota_hero_templar_assassin': 'Slayer',
        'npc_dota_hero_rattletrap': 'Gunner',
        'npc_dota_hero_zuus': 'Wizard',
        'npc_dota_hero_bloodseeker': 'Shaman',
        'npc_dota_hero_sharpshooter': 'Sharpshooter',
    },
    DUNGEON_NAMES: [
        'butchers_sepulcher',
        'desolate_stockade',
        'abandoned_mine',
        'centaur_arena',
        'wolfs_cave',
        'harpy_peak',
        'dire_sanctuary',
        'satyr_seer',
        'satyr_conjuror',
        'satyr_demon',
        'satyr_lord',
        'ice_lair',
        'underpass',
        'jungle_temple',
        'sunken_city',
        'lost_woods',
        'desert_pyramid',
        'magma_core',
        'trial_of_flame',
        'abyssal_stronghold',
    ],
};