/* eslint-disable no-inline-comments */
module.exports = {
    BOT_USER_ID: '',
    BOT_CHANNEL_ID: '',
    BOT_CATEGORY_ID: '',
    GUILD_ID: '',
    MOD_ROLE_ID: '350238304924336128',
    DEV_ID: '162434234357645312',
    SUGGESTIONS_CHANNEL_ID: '604811853503266816',
    MAP: 'https://i.imgur.com/kDIh5uF.png',
    REINCARNATIONS: 'https://i.imgur.com/npEmtsf.png',
    MINING_NODES: 'https://i.imgur.com/xla6iOC.png',
    INFUSIONS: 'https://i.imgur.com/bbDlfpp.png',
    NEW_MEMBER_DATA: {
        'name': '',
        'warnings': 0,
        'tempBans': 0,
        'cookies': 0,
        'warningreasons': [],
        'mutecount': 0,
        'mutehistory': ['\u200B'],
        'steamid': '',
    },
    HERO_LIST: {
        'npc_dota_hero_kunkka': 'Novice',
        'npc_dota_hero_dragon_knight': 'Warrior',
        'npc_dota_hero_invoker': 'Devout',
        'npc_dota_hero_windrunner': 'Ranger',
        'npc_dota_hero_bounty_hunter': 'Rogue',
        'npc_dota_hero_warlock': 'Mage',
        'npc_dota_hero_axe': 'Brute',
        'npc_dota_hero_juggernaut': 'Samurai',
        'npc_dota_hero_swordsman': 'Swordsman',
        'npc_dota_hero_furion': 'Exile',
        'npc_dota_hero_lina': 'Elementalist',
        'npc_dota_hero_troll_warlord': 'Monk',
        'npc_dota_hero_dazzle': 'Cultist',
        'npc_dota_hero_sniper': 'Hunter',
        'npc_dota_hero_riki': 'Wetboy',
        'npc_dota_hero_crystal_maiden': 'Arcanist',
        'npc_dota_hero_phantom_lancer': 'Lancer',
        'npc_dota_hero_beastmaster': 'Barbarian',
        'npc_dota_hero_brewmaster': 'Exile',
        'npc_dota_hero_drow_ranger': 'Marksman',
        'npc_dota_hero_sven': 'Zerker',
        'npc_dota_hero_silencer': 'Runecaster',
        'npc_dota_hero_arc_warden': 'Technologist',
        'npc_dota_hero_legion_commander': 'Avenger',
        'npc_dota_hero_omniknight': 'Paragon',
        'npc_dota_hero_keeper_of_the_light': 'Bishop',
        'npc_dota_hero_chaos_knight': 'Daeagon',
        'npc_dota_hero_ember_spirit': 'Bladerider',
        'npc_dota_hero_oracle': 'Chronomancer',
        'npc_dota_hero_phantom_assassin': 'Spectre',
        'npc_dota_hero_rubick': 'Wetboy',
        'npc_dota_hero_vengefulspirit': 'Witch',
        'npc_dota_hero_spectre': 'Shadow_Assassin',
        'npc_dota_hero_huskar': 'Beast',
        'npc_dota_hero_chen': 'Bishop',
        'npc_dota_hero_earth_spirit': 'Martial-Artist',
        'npc_dota_hero_antimage': 'Bloodmage',
        'npc_dota_hero_skeleton_king': 'Knight',
        'npc_dota_hero_mirana': 'Priestess',
        'npc_dota_hero_templar_assassin': 'Slayer',
        'npc_dota_hero_rattletrap': 'Gunner',
        'npc_dota_hero_zuus': 'Wizard',
        'npc_dota_hero_bloodseeker': 'Shaman',
        'npc_dota_hero_sharpshooter': 'Sharpshooter',
        /*
        'npc_dota_hero_bounty_hunter': 'Rogue',
        'npc_dota_hero_Rogue': 'Rogue',
        'npc_dota_hero_windrunner': 'Ranger',
        'npc_dota_hero_ranger': 'Ranger',
        'npc_dota_hero_warlock': 'Mage',
        'npc_dota_hero_mage': 'Mage',
        'npc_dota_hero_devout': 'Devout',
        'npc_dota_hero_invoker': 'Devout',
        'npc_dota_hero_axe': 'Brute',
        'npc_dota_hero_brute': 'Brute',
        'npc_dota_hero_novice_protagonist': 'Hero',
        'npc_dota_hero_kunkka': 'Hero',
        'npc_dota_hero_avenger': 'Avenger',
        'npc_dota_hero_wisp': 'Unbidden',
        'npc_dota_hero_sven': 'Zerker',
        'npc_dota_hero_zerker': 'Zerker',
        'npc_dota_hero_disruptor': 'Wizard',
        'npc_dota_hero_zuus': 'Wizard',
        'npc_dota_hero_wizard': 'Wizard',
        'npc_dota_hero_vengefulspirit': 'Witch',
        'npc_dota_hero_witch': 'Witch',
        'npc_dota_hero_rubick': 'Trickster',
        'npc_dota_hero_trickster': 'Trickster',
        'npc_dota_hero_arc_warden': 'Technologist',
        'npc_dota_hero_technologist': 'Technologist',
        'npc_dota_hero_templar_assassin': 'Slayer',
        'npc_dota_hero_slayer': 'Slayer',
        'npc_dota_hero_meepo': 'Geomancer',
        'npc_dota_hero_geomancer': 'Geomancer',
        'npc_dota_hero_bishop': 'Bishop',
        'npc_dota_hero_chen': 'Bishop',
        'npc_dota_hero_beast_handler': 'Beast Handler',
        'npc_dota_hero_huskar': 'Beast Handler',
        'npc_dota_hero_legion_commander': 'Avenger',
        'npc_dota_hero_riki': 'Wetboy',
        'npc_dota_hero_wetboy': 'Wetboy',
        'npc_dota_hero_swordsman': 'Swordsman',
        'npc_dota_hero_omniknight': 'Priest',
        'npc_dota_hero_priest': 'Priest',
        'npc_dota_hero_troll_warlord': 'Monk',
        'npc_dota_hero_lone_druid': 'Monk',
        'npc_dota_hero_monk': 'Monk',
        'npc_dota_hero_drow_ranger': 'Marksman',
        'npc_dota_hero_marksman': 'Marksman',
        'npc_dota_hero_phantom_lancer': 'Lancer',
        'npc_dota_hero_lancer': 'Lancer',
        'npc_dota_hero_sniper': 'Hunter',
        'npc_dota_hero_hunter': 'Hunter',
        'npc_dota_hero_furion': 'Exiled',
        'npc_dota_hero_exile': 'Exile',
        'npc_dota_hero_silencer': 'Runecaster',
        'npc_dota_hero_runecaster': 'Runecaster',
        'npc_dota_hero_mirana': 'Priestess',
        'npc_dota_hero_priestess': 'Priestess',
        'npc_dota_hero_keeper_of_the_light': 'Paragon',
        'npc_dota_hero_paragon': 'Paragon',
        'npc_dota_hero_paladin': 'Paladin',
        'npc_dota_hero_earth_spirit': 'Martial Artist',
        'npc_dota_hero_martial_artist': 'Martial Artist',
        'npc_dota_hero_skeleton_king': 'Knight',
        'npc_dota_hero_knight': 'Knight',
        'npc_dota_hero_rattletrap': 'Gunner',
        'npc_dota_hero_gunner': 'Gunner',
        'npc_dota_hero_phantom_assassin': 'Fencer',
        'npc_dota_hero_fencer': 'Fencer',
        'npc_dota_hero_treant': 'Druid',
        'npc_dota_hero_brewmaster': 'Druid',
        'npc_dota_hero_druid': 'Druid',
        'npc_dota_hero_chaos_knight': 'Daeagon',
        'npc_dota_hero_daeagon': 'Daeagon',
        'npc_dota_hero_oracle': 'Chronomancer',
        'npc_dota_hero_chronomancer': 'Chronomancer',
        'npc_dota_hero_blood_mage': 'Blood Mage',
        'npc_dota_hero_antimage': 'Blood Mage',
        'npc_dota_hero_ember_spirit': 'Bladerider',
        'npc_dota_hero_bladerider': 'Bladerider',
        'npc_dota_hero_beastmaster': 'Barbarian',
        'npc_dota_hero_barbarian': 'Barbarian',
        'npc_dota_hero_dragon_knight': 'Warrior',
        'npc_dota_hero_warrior': 'Warrior',
        'npc_dota_hero_spellblade': 'Spellblade',
        'npc_dota_hero_sharpshooter': 'Sharpshooter',
        'npc_dota_hero_crystal_maiden': 'Arcanist',
        'npc_dota_hero_arcanist': 'Arcanist',
        'npc_dota_hero_cultist': 'Cultist',
        'npc_dota_hero_dazzle': 'Cultist',
        'npc_dota_hero_lina': 'Elementalist',
        'npc_dota_hero_elementalist': 'Elementalist',
        'npc_dota_hero_bloodseeker': 'Shaman',
        'npc_dota_hero_shaman': 'Shaman',
        'npc_dota_hero_spectre': 'Shadow Assassin',
        'npc_dota_hero_shadow_assassin': 'Shadow Assassin',
        'npc_dota_hero_juggernaut': 'Samurai',
        */
    },
    DUNGEON_NAMES: [
        'butchers_sepulcher',
        'desolate_stockade',
        'abandoned_mine',
        'centaur_arena',
        'wolfs_cave',
        'harpy_peak',
        'dire_sanctuary',
        'satyr_seer',
        'satyr_conjuror',
        'satyr_demon',
        'satyr_lord',
        'ice_lair',
        'underpass',
        'jungle_temple',
        'sunken_city',
        'lost_woods',
        'desert_pyramid',
        'magma_core',
        'trial_of_flame',
        'abyssal_stronghold',
    ],
};